spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:orderapp
    driverClassName: org.h2.Driver
    password: password
  application:
    name: Manages-customer-orders
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka