spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:inventoryapp
    driverClassName: org.h2.Driver
    password: password
  application:
    name: Inventory-Management-System
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: '9090'
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka