server:
  ssl:
    key-store-password: 123456
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-alias: ecomerce
spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:orderapp
    driverClassName: org.h2.Driver
    password: password
  application:
    name: Product-Catalog-Caching
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
